### ISSUE TITLE
Preserve `t` param of bilibili link after purifing

### ISSUE THREAD

**Issue by sxzz** [sxyazi/bendan#4]
`https://www.bilibili.com/video/BV16j411U7je/?t=25.1`

Expected: `https://www.bilibili.com/video/av445617998/?t=25.1`
Actual: `https://www.bilibili.com/video/av445617998`

`t` param is a decimal number.

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/sxyazi/bendan/commit/f01595c77ebb9d4e4be6e8f395134a2123a2ad4b.

BTW that video title is amazingly cute, I love it! ☺️
